stages:
  - deploy
  # - test

# test:
#   stage: test
#   image: golang:latest
#   script:
#     - cd GoAttendEasy
#     - go test -v ./.. 
#   only:
#     - master

deploy:
  stage: deploy
  image: flyio/flyctl:latest
  only:
    - master
  script:
    - ls
    - flyctl auth login -t "$FLY_TOKEN"
    - flyctl deploy --now --app "go-attend-easy"
