# TODO: fix this
stages:
  - test
  - deploy

checkout:
  script:
    - git clone https://gitlab.com/irdaislakhuafa/GoAttendEasy.git
    - cd GoAttendEasy

test:
  stage: test
  image: golang:latest
  script:
    - go test -v ./.. 
  only:
    - master
c
deploy:
  stage: deploy
  image: flyio/flyctl:latest
  only:
    - master
  script:
    - flyctl auth login -t "$FLY_TOKEN"
    - flyctl deploy --now --app "go-attend-easy"
